import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, CalendarDays, Sparkles, Utensils } from "lucide-react";
import privateDiningImage from "@/assets/private-dining-room.jpg";
import specialEventImage from "@/assets/special-dining-event.jpg";
import birthdayOccasionImage from "@/assets/private-occasion-birthday.jpg";
import { Button } from "@/components/ui/button";
import { Eyebrow, PageFrame, PageHero, Reveal } from "@/components/sv-grand";
import { images } from "@/lib/sv-grand-data";

export const Route = createFileRoute("/experience")({ head: () => ({ meta: [{ title: "Dining Experiences — AUREVIA" }, { name: "description", content: "Explore private dining, chef-led tasting menus and special events at AUREVIA Bengaluru." }, { property: "og:title", content: "Dining Experiences — AUREVIA" }, { property: "og:description", content: "Remarkable food, intimate tables and deeply personal hosting." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: ExperiencePage });
const moments = [
  { icon: Sparkles, title: "Chef-led dining", text: "Seasonal menus and intimate tastings shaped around the best produce of the day.", image: images.chefImage, alt: "AUREVIA chef preparing a dish" },
  { icon: Utensils, title: "Private dining", text: "A considered table for celebrations, conversations and occasions worth lingering over.", image: privateDiningImage, alt: "AUREVIA private dining room with prepared tables" },
  { icon: CalendarDays, title: "Special events", text: "Visiting chefs, regional showcases and one-night-only menus throughout the year.", image: specialEventImage, alt: "AUREVIA special dining event with decorated tables and stage" },
];
function ExperiencePage() { return <PageFrame><PageHero eyebrow="Dining experiences" title={<>The luxury<br/><span className="text-gold-soft">of attention.</span></>} copy="At AUREVIA, every course, table and detail is composed for the pleasure of dining." image={images.interiorImage}/><section className="px-6 py-28 sm:px-10 lg:px-16 lg:py-40"><div className="mx-auto max-w-[1280px]"><Reveal className="grid gap-px bg-border md:grid-cols-3">{moments.map(({ icon: Icon, title, text, image, alt }, index) => <article key={title} className="bg-background p-8 sm:p-10"><div className="overflow-hidden"><img src={image} alt={alt} loading="lazy" width={900} height={620} className="aspect-[4/3] w-full object-cover transition duration-700 hover:scale-[1.03]" /></div><p className="mt-8 font-display text-6xl text-primary/20">0{index + 1}</p><Icon className="mt-8 size-7 stroke-1 text-primary"/><h2 className="mt-6 font-display text-3xl text-ivory">{title}</h2><p className="mt-4 text-sm font-light leading-7 text-muted-foreground">{text}</p></article>)}</Reveal></div></section><section className="grid min-h-[720px] lg:grid-cols-2"><div className="relative min-h-[480px]"><img src={birthdayOccasionImage} alt="Private occasion celebration at AUREVIA" loading="lazy" width={1600} height={1067} className="absolute inset-0 h-full w-full object-cover"/></div><Reveal className="flex items-center bg-card px-7 py-20 sm:px-14 lg:px-20"><div><Eyebrow>Private occasions</Eyebrow><h2 className="mt-7 font-display text-4xl leading-tight text-ivory sm:text-6xl">Celebrations,<br/>held beautifully.</h2><p className="mt-7 max-w-xl text-sm font-light leading-8 text-muted-foreground">Intimate dinners, milestone evenings and thoughtful gatherings are composed around you—from a bespoke menu to the final candle.</p><Button variant="luxury" asChild className="mt-9"><Link to="/contact">Plan an occasion <ArrowRight/></Link></Button></div></Reveal></section></PageFrame>; }