import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowDown, ArrowRight, Quote } from "lucide-react";
import { useEffect, useRef, useState, type MouseEvent } from "react";

import introVideo from "@/assets/aranyam-intro.mp4.asset.json";
import { Button } from "@/components/ui/button";
import { DishCard, Eyebrow, PageFrame, Reveal } from "@/components/sv-grand";
import { featuredDishes, images } from "@/lib/sv-grand-data";

const introVideoUrl =
  typeof introVideo?.url === "string" && !introVideo.url.startsWith("/__l5e/assets-v1/")
    ? introVideo.url
    : null;

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "AUREVIA — Luxury Indian Restaurant in Bengaluru" },
    { name: "description", content: "Discover AUREVIA’s fire-led Indian fine dining in Bengaluru." },
    { property: "og:title", content: "AUREVIA — Fine Dining, Considered" },
    { property: "og:description", content: "A luxury Bengaluru restaurant shaped around remarkable food and generous hosting." },
    { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
  ] }),
  component: HomePage,
});

function HomePage() {
  const [intro, setIntro] = useState(true);
  const [leaving, setLeaving] = useState(false);
  const hero = useRef<HTMLElement>(null);
  const close = () => { setLeaving(true); window.setTimeout(() => setIntro(false), 900); };
  useEffect(() => { const timer = window.setTimeout(close, window.matchMedia("(prefers-reduced-motion: reduce)").matches ? 400 : 4600); return () => window.clearTimeout(timer); }, []);
  const move = (event: MouseEvent<HTMLElement>) => { if (!hero.current || window.matchMedia("(prefers-reduced-motion: reduce)").matches) return; const rect = hero.current.getBoundingClientRect(); hero.current.style.setProperty("--mx", `${((event.clientX - rect.left) / rect.width - .5) * 16}px`); hero.current.style.setProperty("--my", `${((event.clientY - rect.top) / rect.height - .5) * 10}px`); };
  return <PageFrame>
    {intro && <div className="intro-auto-hide fixed inset-0 z-[100]"><div className={`absolute inset-0 overflow-hidden bg-background ${leaving ? "animate-intro-leave" : ""}`}>{introVideoUrl ? <video autoPlay muted playsInline className="absolute inset-0 h-full w-full object-cover opacity-70"><source src={introVideoUrl} type="video/mp4"/></video> : <img src={images.exteriorImage} alt="AUREVIA exterior" className="absolute inset-0 h-full w-full object-cover opacity-70" />}<div className="cinematic-vignette absolute inset-0"/><div className="relative z-10 flex h-full flex-col items-center justify-center px-6 text-center"><p className="animate-intro-sub mb-5 text-[0.62rem] uppercase tracking-[0.4em] text-gold-soft">Bengaluru · India</p><h1 className="animate-intro-word font-display text-5xl text-ivory sm:text-8xl">AUREVIA</h1><div className="gold-rule animate-line-grow my-7 h-px w-48"/><p className="animate-intro-sub text-xs uppercase tracking-[0.32em] text-ivory/75">Fine dining, considered</p></div><Button variant="ghost" onClick={close} className="absolute bottom-8 right-6 z-20 text-[0.6rem] uppercase tracking-[0.24em] text-ivory/70 hover:bg-transparent hover:text-primary sm:right-8">Skip film <ArrowRight/></Button></div></div>}
    <section ref={hero} onMouseMove={move} className="relative min-h-[calc(100svh-5rem)] overflow-hidden"><img src={images.exteriorImage} alt="AUREVIA at blue hour" width={1600} height={1067} className="absolute inset-0 h-[106%] w-[106%] -translate-x-[3%] -translate-y-[3%] object-cover opacity-70 [transform:translate(var(--mx,0),var(--my,0))_scale(1.03)] transition-transform duration-500"/><div className="cinematic-vignette absolute inset-0"/><div className="relative mx-auto flex min-h-[calc(100svh-5rem)] max-w-[1440px] flex-col justify-end px-6 pb-14 sm:px-10 lg:px-16 lg:pb-20"><p className="mb-6 text-[0.6rem] uppercase tracking-[0.35em] text-primary">Luxury restaurant · Bengaluru</p><h1 className="max-w-5xl font-display text-[clamp(3.5rem,8vw,8rem)] leading-[0.96] text-ivory">A grand table.<br/><span className="text-gold-soft">A personal welcome.</span></h1><div className="mt-9 flex flex-col items-start justify-between gap-7 border-t border-foreground/20 pt-7 sm:flex-row sm:items-end"><p className="max-w-lg text-sm font-light leading-7 text-ivory/70">Fire-led Indian fine dining, generous hosting, and a kitchen led by Chef Narayana.</p><Button variant="luxury" asChild><Link to="/experience">Discover AUREVIA <ArrowRight/></Link></Button></div></div><ArrowDown className="absolute bottom-6 left-1/2 z-10 size-4 animate-drift text-primary"/></section>
    <section className="px-6 py-28 sm:px-10 lg:px-16 lg:py-40"><Reveal className="mx-auto grid max-w-[1280px] gap-16 lg:grid-cols-[.85fr_1.15fr] lg:items-center"><div className="relative"><div className="absolute -left-4 -top-4 h-full w-full border border-primary/35"/><img src={images.feastImage} alt="The AUREVIA dining table" loading="lazy" width={1600} height={1067} className="relative aspect-[4/5] w-full object-cover"/></div><div className="lg:pl-10"><Eyebrow>At the table</Eyebrow><h2 className="mt-7 font-display text-4xl leading-tight text-ivory sm:text-6xl">India’s many kitchens.<br/>One generous table.</h2><p className="mt-7 max-w-xl text-sm font-light leading-8 text-muted-foreground">Chef Narayana moves from coastal hearths to royal dum kitchens with curiosity and restraint—honouring vegetarian and non-vegetarian traditions equally.</p><Button variant="luxuryOutline" asChild className="mt-9"><Link to="/menu">Explore the menu <ArrowRight/></Link></Button></div></Reveal></section>
    <section className="border-y border-border bg-card px-6 py-28 sm:px-10 lg:px-16 lg:py-36"><div className="mx-auto max-w-[1280px]"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><Eyebrow>Chef’s signatures</Eyebrow><h2 className="mt-6 font-display text-4xl text-ivory sm:text-6xl">Four stories of fire.</h2></div><Link to="/menu" className="flex items-center gap-3 text-[0.6rem] uppercase tracking-[0.18em] text-primary">View all dishes <ArrowRight className="size-4"/></Link></div><div className="stories-fire mt-12"><div className="stories-fire-track">{featuredDishes.map((dish, index) => <div className="stories-fire-card" key={dish.slug}><DishCard dish={dish} index={index}/></div>)}{featuredDishes.map((dish, index) => <div className="stories-fire-card" key={`${dish.slug}-loop`} aria-hidden="true"><DishCard dish={dish} index={index}/></div>)}</div></div></div></section>
    <section className="grid min-h-[760px] lg:grid-cols-2"><div className="relative min-h-[560px] overflow-hidden"><img src={images.chefImage} alt="Chef Narayana at AUREVIA" loading="lazy" width={1280} height={1600} className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-background/60 to-transparent"/></div><Reveal className="flex items-center px-7 py-24 sm:px-14 lg:px-20"><div className="max-w-xl"><Eyebrow>Chef Narayana</Eyebrow><Quote className="mt-10 size-8 stroke-1 text-primary"/><blockquote className="mt-7 font-display text-3xl leading-snug text-ivory sm:text-5xl">“The finest welcome is a dish that feels remembered, even when tasted for the first time.”</blockquote><p className="mt-8 text-sm font-light leading-8 text-muted-foreground">A career shaped by temple kitchens, coastal markets and India’s most celebrated culinary traditions now finds its most personal expression at AUREVIA.</p><Button variant="luxuryOutline" asChild className="mt-9"><Link to="/chef">Meet the chef <ArrowRight/></Link></Button></div></Reveal></section>
    <section className="px-6 py-28 text-center sm:px-10 lg:py-36"><Reveal className="mx-auto max-w-4xl"><Eyebrow>Dining notes</Eyebrow><Quote className="mx-auto mt-10 size-8 stroke-1 text-primary"/><p className="mt-7 font-display text-3xl leading-relaxed text-ivory sm:text-5xl">“A restaurant with the confidence to whisper. Every detail feels personal, and every plate has a point of view.”</p><p className="mt-7 text-[0.58rem] uppercase tracking-[0.2em] text-muted-foreground">The Bengaluru Edit</p><Button variant="luxury" asChild className="mt-10"><Link to="/reserve">Plan your evening <ArrowRight/></Link></Button></Reveal></section>
  </PageFrame>;
}