import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { ArrowLeft, ArrowRight, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import { DishCard, Eyebrow, PageFrame, Reveal } from "@/components/sv-grand";
import { dishes } from "@/lib/sv-grand-data";

export const Route = createFileRoute("/menu/$slug")({
  loader: ({ params }) => { const dish = dishes.find((item) => item.slug === params.slug); if (!dish) throw notFound(); return { dish }; },
  head: ({ loaderData }) => ({ meta: [{ title: loaderData ? `${loaderData.dish.name} — SV Grand` : "Dish not found — SV Grand" }, { name: "description", content: loaderData?.dish.story ?? "Explore the menu at SV Grand." }, { property: "og:title", content: loaderData ? `${loaderData.dish.name} — SV Grand` : "SV Grand Menu" }, { property: "og:description", content: loaderData?.dish.note ?? "Chef Narayana’s Indian dining menu." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }),
  notFoundComponent: () => <PageFrame><main className="flex min-h-[70svh] flex-col items-center justify-center px-6 text-center"><Eyebrow>Not on tonight’s menu</Eyebrow><h1 className="mt-6 font-display text-5xl text-ivory">This dish has moved on.</h1><Button variant="luxury" asChild className="mt-8"><Link to="/menu">Return to the menu</Link></Button></main></PageFrame>,
  component: DishPage,
});

function DishPage() { const { dish } = Route.useLoaderData(); const related = dishes.filter((item) => item.kind === dish.kind && item.slug !== dish.slug).slice(0, 3); const ingredients = dish.ingredients ?? dish.note.split(" · "); return <PageFrame><main><section className="grid min-h-[calc(100svh-5rem)] lg:grid-cols-[1.1fr_.9fr]"><div className="relative min-h-[55svh] overflow-hidden"><img src={dish.image} alt={dish.name} width={1600} height={1067} className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-background/55 to-transparent"/><Link to="/menu" className="absolute left-6 top-6 flex items-center gap-2 text-[0.58rem] uppercase tracking-[0.18em] text-ivory hover:text-primary"><ArrowLeft className="size-4"/>All dishes</Link></div><div className="flex items-center px-7 py-20 sm:px-14 lg:px-20"><Reveal className="max-w-xl"><div className="flex items-center gap-3"><span className={`size-2 rounded-full ${dish.kind === "Vegetarian" ? "bg-veg" : "bg-nonveg"}`}/><Eyebrow>{dish.kind} · {dish.course}</Eyebrow></div><h1 className="mt-7 font-display text-5xl leading-tight text-ivory sm:text-7xl">{dish.name}</h1><p className="mt-5 text-sm leading-7 text-gold-soft">{dish.note}</p><p className="mt-8 text-sm font-light leading-8 text-muted-foreground">{dish.story}</p><div className="mt-8 border-y border-border py-5"><p className="eyebrow">Created by</p><p className="mt-2 font-display text-2xl text-ivory">{dish.chef}</p></div><div className="mt-7 grid gap-5 border-b border-border pb-6 sm:grid-cols-2"><div><p className="eyebrow mb-3">Ingredients</p>{ingredients.map((ingredient) => <p key={ingredient} className="flex items-center gap-3 py-1.5 text-xs text-muted-foreground"><Check className="size-4 shrink-0 text-primary"/>{ingredient}</p>)}</div><div><p className="eyebrow mb-3">Kitchen notes</p>{dish.highlights.map((highlight) => <p key={highlight} className="flex items-center gap-3 py-1.5 text-xs text-muted-foreground"><Check className="size-4 shrink-0 text-primary"/>{highlight}</p>)}</div></div><div className="mt-9 flex items-center justify-between"><p className="font-display text-3xl text-gold-soft">{dish.price}</p><Button variant="luxury" asChild><Link to="/reserve">Reserve a table <ArrowRight/></Link></Button></div></Reveal></div></section><section className="border-t border-border bg-card px-6 py-24 sm:px-10 lg:px-16"><div className="mx-auto max-w-[1280px]"><Eyebrow>You may also enjoy</Eyebrow><div className="mt-10 grid gap-8 md:grid-cols-3">{related.map((item) => <DishCard key={item.slug} dish={item}/>)}</div></div></section></main></PageFrame>; }